name = "unleashed-shopify-sync-v2"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "AUTH_STORE"
id = "f561e9dfc8774ea4bb5fc9a877bbb8c4" 

# Queue producers for sending mutations to the mutation worker
# This worker only produces queue messages, doesn't consume them

# Queue for product mutations
[[queues.producers]]
queue = "product-mutations"
binding = "PRODUCT_QUEUE"

# Queue for location mutations
[[queues.producers]]
queue = "location-mutations"
binding = "LOCATION_QUEUE"

# Queue for customer mutations
[[queues.producers]]
queue = "customer-mutations"
binding = "CUSTOMER_QUEUE"

# Environment variables for logging
[vars]
LOG_LEVEL = "info" 