name = "unleashed-shopify-sync-mutation-worker"
main = "mutation-worker.js"
compatibility_date = "2024-01-01"

# KV namespace for authentication data
[[kv_namespaces]]
binding = "AUTH_STORE"
id = "f561e9dfc8774ea4bb5fc9a877bbb8c4"

# Queue consumers for processing mutations
# This worker only consumes from queues, doesn't produce

# Product mutations queue consumer
[[queues.consumers]]
queue = "product-mutations"
max_batch_size = 1
max_batch_timeout = 30

# Location mutations queue consumer  
[[queues.consumers]]
queue = "location-mutations"
max_batch_size = 1
max_batch_timeout = 30

# Customer mutations queue consumer
[[queues.consumers]]
queue = "customer-mutations"
max_batch_size = 1
max_batch_timeout = 30

# Environment variables for logging
[vars]
LOG_LEVEL = "info" 